### ISSUE TITLE
Kotlin 1.4 breaks ktlint api: java.lang.NoSuchFieldError: FUN_KEYWORD

### ISSUE THREAD

**Issue by stephanenicolas** [pinterest/ktlint#771]
Using kotlin 1.4 M2, 

I got these errors in a test: 
```
java.lang.NoSuchFieldError: FUN_KEYWORD
	at com.pinterest.ktlint.core.ast.ElementType.<clinit>(ElementType.kt:154)
```
and 
```
java.lang.NoClassDefFoundError: Could not initialize class com.pinterest.ktlint.core.ast.ElementType
```

More generally speaking, is there a plan to have ktlint working with kotlin 1.4 ?

**Comment by stephanenicolas** [comment]
I forked the repo and yes, definitely the problem is the field `FUN_KEYWORD` in `KtTokens` that is used from ktlint's `ElementType`.

**Comment by shashachu** [comment]
@stephanenicolas hi, thanks for the report and for digging in to root cause. Yes, we will update to support 1.4, likely once it's been officially released.

**Comment by stephanenicolas** [comment]
@shashachu I understand that other aspects of the plugin and its maintenance also require work.
I totally get that and thx for all the work you're doing.

Nonetheless, we cannot test our build and prepare our own migration due to this bug and I guess we're not the only ones. 
I tried to check a bit more but I am really not confident on how to address the issue. 

Is there a way this issue could be prioritized so that we could test other aspects of our builds. Ideally we would be early adopters of kotlin 1.4 which is already in M2 stage. 
We have a very large build and we work often with people from JB to optimize the performance of the kotlin tooling. Fixing this bug would help us to enhance the next kotlin version for the whole community.

**Comment by shashachu** [comment]
@stephanenicolas when you have a chance, can you just add a little more detail about your setup and how you're running your tests? Thanks!

**Comment by Tapchicoma** [comment]
As one of the things that should address this - we are planning to start publishing snapshots that will use kotlin-in-development versions.

**Comment by henrik242** [comment]
Kotlin 1.4.0 has been released: https://github.com/JetBrains/kotlin/releases/tag/v1.4.0

**Comment by pwgraham91** [comment]
Kotlin 1.4.0 does not fix the issue for me

**Comment by ZacSweers** [comment]
This should be folded into #830 to de-dupe issues

**Comment by romtsn** [comment]
yep, please track this in #830 (there's already a `0.38.0-alpha01` version that should resolve the aforementioned issue)
